### ISSUE TITLE
File path omitted in 'unknown type'

### ISSUE THREAD

**Issue by jtrees** [erlang-labs/dialyzer#2]
When getting the `unknown_type` warning, the file path (and line) is omitted. This makes debugging very hard.

For example:

```
[{:warn_unknown, {[], 0}, {:unknown_type, {DoesNotExist, :t, 0}}}]
```

This [also affects upstream Elixir projects](https://github.com/jeremyjh/dialyxir/issues/102), such as [dialyxir](https://github.com/jeremyjh/dialyxir).

**Comment by garazdawi** [comment]
Please report this at https://erlang.org/erlang/otp
